---
- hosts: localhost

  tasks:
    - name: Copy MathLibrary to server
      copy:
              src: src/c/testcode/mathLibTest
              dest: /tmp/mathLibTest
      notify:
        - install package 

  handlers:
    - name: install package
      dnf:
              name: /tmp/mathLibTest
              state: present