---
- hosts: localhost

  tasks:
    - name: Copy rpm to server
      copy:
              src: package.rpm
              dest: /var/tmp/package.rpm
      notify:
        - install rpm 

  handlers:
    - name: install rpm
      yum:
              name: /var/tmp/package.rpm
              state: present 
